receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"

processors:
  batch:
    timeout: 500ms                 # Even more frequent for maximum throughput
    send_batch_size: 1024         # Very small batches = highest throughput
    send_batch_max_size: 2048     # Conservative maximum
  memory_limiter:
    limit_mib: 1024               # More memory for high throughput
    check_interval: 500ms         # More frequent memory checks

exporters:
  otlphttp:
    endpoint: http://ingestor:8000
    timeout: 10s
    encoding: json
    compression: none
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 30s
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [otlphttp, debug]